package com.example.finance.account.messaging;

// ── DATADOG INSTRUMENTATION ──────────────────────────────────────────
// Step 10 — Data Streams Monitoring (DSM) for JMS producers.
// DSM tracks end-to-end pipeline latency: producer → broker → consumer.
// It measures consumer lag, queue depth trends, and pathway throughput.
//
// Uncomment to enable the producer checkpoint on outbound JMS messages:
//
// import datadog.trace.api.experimental.DataStreamsCheckpointer;
//
// Docs: https://docs.datadoghq.com/data_streams/java/
// Requires: DD_DATA_STREAMS_ENABLED=true
// ─────────────────────────────────────────────────────────────────────

import com.example.finance.account.model.Account;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.stereotype.Component;

import jakarta.jms.Session;
import java.util.Map;

/**
 * Publishes account lifecycle events to ActiveMQ Artemis queues.
 *
 * Queues:
 *   fraud.score.queue — consumed by fraud-detection service (Python)
 *   alert.queue       — consumed by notification-service (Go)
 *
 * JMS span names generated by dd-java-agent (auto-instrumented):
 *   jms.produce — on every send
 *   jms.consume — on every receive (consumer side)
 *
 * Finance span tags on the auto-instrumented jms.produce span:
 *   messaging.destination → queue name (bounded set — safe cardinality)
 *   messaging.message_id  → broker-assigned message ID
 *
 * WARNING — High cardinality: do NOT use raw transaction/account IDs
 * as span tags. Use messaging.message_id only for producer↔consumer
 * correlation, not as a filtering dimension.
 * Docs: https://docs.datadoghq.com/tagging/assigning_tags/#defining-tags
 */
@Component
public class PaymentEventProducer {

    private static final Logger log = LoggerFactory.getLogger(PaymentEventProducer.class);

    static final String FRAUD_SCORE_QUEUE = "fraud.score.queue";
    static final String ALERT_QUEUE = "alert.queue";

    private final JmsTemplate jmsTemplate;

    public PaymentEventProducer(JmsTemplate jmsTemplate) {
        this.jmsTemplate = jmsTemplate;
    }

    /**
     * Sends an account-created event to fraud.score.queue.
     * The fraud-detection service consumes this asynchronously and assigns a risk score.
     *
     * DSM (Step 10): setProducerCheckpoint marks this message in the pipeline,
     * enabling consumer lag visibility from account-service → fraud-detection.
     */
    public void sendAccountCreatedEvent(Account account) {
        var payload = Map.of(
                "eventType", "account.created",
                "accountId", account.getId(),
                "tier", account.getTier(),
                "currency", account.getCurrency()
                // NOTE: balance and ownerId intentionally omitted — PII / sensitive financial data.
                // Resolve these in the consumer service using the accountId reference.
        );

        log.info("event=jms.produce queue={} event_type=account.created account_tier={} currency={}",
                FRAUD_SCORE_QUEUE, account.getTier(), account.getCurrency());

        try {
            jmsTemplate.send(FRAUD_SCORE_QUEUE, session -> {
                var message = session.createTextMessage(toJson(payload));

                // ── DATADOG INSTRUMENTATION ──────────────────────────────────────────
                // Step 10 — Uncomment to set the DSM producer checkpoint on this message.
                // This marks the pipeline entry point for end-to-end latency measurement.
                //
                // DataStreamsCheckpointer.get().setProducerCheckpoint(
                //     message,                 // javax.jms.Message — headers are injected
                //     "jms",                   // pathway type
                //     FRAUD_SCORE_QUEUE        // destination name (bounded, safe cardinality)
                // );
                //
                // What this enables in the Datadog UI:
                //   - Pathway map: account-service → fraud.score.queue → fraud-detection
                //   - Consumer lag alert: detect fraud scoring backlog before it delays payments
                //   - End-to-end latency SLA: time from account creation to fraud score
                //
                // Docs: https://docs.datadoghq.com/data_streams/java/
                // ─────────────────────────────────────────────────────────────────────

                return message;
            });

            log.info("event=jms.produce status=sent queue={}", FRAUD_SCORE_QUEUE);

        } catch (Exception e) {
            log.error("event=jms.produce status=error queue={} error_type={} message={}",
                    FRAUD_SCORE_QUEUE, e.getClass().getSimpleName(), e.getMessage());

            // ── DATADOG INSTRUMENTATION ──────────────────────────────────────────
            // Step 5 — Uncomment to mark the active APM span as an error:
            //
            // import io.opentracing.util.GlobalTracer;
            // import datadog.trace.api.DDTags;
            // import io.opentracing.tag.Tags;
            // var activeSpan = GlobalTracer.get().activeSpan();
            // if (activeSpan != null) {
            //     activeSpan.setTag(Tags.ERROR, true);
            //     activeSpan.setTag(DDTags.ERROR_TYPE, e.getClass().getName());
            //     activeSpan.setTag(DDTags.ERROR_MSG, e.getMessage());
            // }
            //
            // Step 6 — Uncomment to increment the JMS error counter:
            // statsd.incrementCounter("jms.produce.errors",
            //     "queue:" + FRAUD_SCORE_QUEUE,
            //     "error_type:" + e.getClass().getSimpleName()
            // );
            // ─────────────────────────────────────────────────────────────────────
        }
    }

    /**
     * Sends a payment-initiated alert to alert.queue.
     * The notification-service (Go) consumes this to dispatch email/SMS stubs.
     */
    public void sendPaymentAlert(String accountId, String currency, String tier) {
        var payload = Map.of(
                "eventType", "payment.initiated",
                "accountId", accountId,
                "currency", currency,
                "tier", tier
        );

        log.info("event=jms.produce queue={} event_type=payment.initiated account_tier={} currency={}",
                ALERT_QUEUE, tier, currency);

        try {
            jmsTemplate.send(ALERT_QUEUE, session -> {
                var message = session.createTextMessage(toJson(payload));

                // ── DATADOG INSTRUMENTATION ──────────────────────────────────────────
                // Step 10 — Uncomment DSM producer checkpoint for the alert queue:
                //
                // DataStreamsCheckpointer.get().setProducerCheckpoint(
                //     message,
                //     "jms",
                //     ALERT_QUEUE
                // );
                // ─────────────────────────────────────────────────────────────────────

                return message;
            });

            log.info("event=jms.produce status=sent queue={}", ALERT_QUEUE);

        } catch (Exception e) {
            log.error("event=jms.produce status=error queue={} error_type={} message={}",
                    ALERT_QUEUE, e.getClass().getSimpleName(), e.getMessage());
        }
    }

    /**
     * Minimal JSON serialisation — replace with Jackson ObjectMapper in production.
     * Jackson is already on the classpath via spring-boot-starter-web.
     */
    private String toJson(Map<String, String> map) {
        var sb = new StringBuilder("{");
        map.forEach((k, v) -> sb.append("\"").append(k).append("\":\"").append(v).append("\","));
        if (sb.charAt(sb.length() - 1) == ',') sb.deleteCharAt(sb.length() - 1);
        sb.append("}");
        return sb.toString();
    }
}
