#!/usr/bin/env bash
# =============================================================================
# generate-eks-kustomization.sh
# Generates deploy/kubernetes/overlays/eks/kustomization.yaml from live
# Terraform output so ECR URLs always match the current AWS account/region.
#
# Called automatically by: make deploy-k8s-eks
# Requires: terraform apply (make tf-apply-aws) to have completed.
# =============================================================================
set -euo pipefail

OUT="deploy/kubernetes/overlays/eks/kustomization.yaml"
TF_DIR="deploy/terraform/aws"

echo "==> Generating $OUT from Terraform output..."

# Read ECR URLs from Terraform once
ECR_JSON=$(cd "$TF_DIR" && terraform output -json ecr_registry_urls 2>/dev/null) || {
  echo "ERROR: terraform output ecr_registry_urls failed."
  echo "       Run 'make tf-apply-aws' before 'make deploy-k8s-eks'."
  exit 1
}

get_url() {
  echo "$ECR_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['$1'])"
}

GW=$(get_url "gateway-api")
AC=$(get_url "account-service")
TX=$(get_url "transaction-service")
FD=$(get_url "fraud-detection")
NS=$(get_url "notification-service")
BP=$(get_url "batch-processor")

cat > "$OUT" << EOF
# =============================================================================
# Kustomize overlay — EKS
# =============================================================================
# AUTO-GENERATED by scripts/generate-eks-kustomization.sh — do not edit.
# Regenerated on every 'make deploy-k8s-eks' from live Terraform output.
# Gitignored: deploy/kubernetes/overlays/eks/kustomization.yaml
#
# ECR registry: $(echo "$GW" | sed 's|/finance-app/gateway-api||')
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/infrastructure
  - ../../base/services
  - storageclass.yaml

images:
  - name: finance-sample-app-gateway-api
    newName: ${GW}
    newTag: latest
  - name: finance-sample-app-account-service
    newName: ${AC}
    newTag: latest
  - name: finance-sample-app-transaction-service
    newName: ${TX}
    newTag: latest
  - name: finance-sample-app-fraud-detection
    newName: ${FD}
    newTag: latest
  - name: finance-sample-app-notification-service
    newName: ${NS}
    newTag: latest
  - name: finance-sample-app-batch-processor
    newName: ${BP}
    newTag: latest

patches:
  # Expose the frontend via an AWS LoadBalancer (NLB) instead of NodePort.
  # EKS nodes are in private subnets so NodePort is not externally reachable.
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: frontend

  # Expose Keycloak via its own NLB so browsers can reach it directly.
  # Same approach as local (NodePort 30089) but with a real external IP.
  # After deploy, patch KEYCLOAK_PUBLIC_URL to the assigned NLB hostname.
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: remove
        path: /spec/ports/0/nodePort
    target:
      kind: Service
      name: keycloak

  # imagePullPolicy: Always — EKS nodes have no local image cache.
  # Applied per-service; frontend (nginx) is excluded as it uses a public image.
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: gateway-api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: account-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: transaction-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: fraud-detection
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: notification-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: batch-processor
EOF

echo "    Written: $OUT"
echo "    ECR base: $(echo "$GW" | sed 's|/finance-app/gateway-api||')"

# ── Update KEYCLOAK_PUBLIC_URL in the base ConfigMap ──────────────────────────────
# On EKS, Keycloak is exposed via a dedicated NLB (LoadBalancer service).
# We get its hostname after the first 'kubectl apply -k' by waiting for the
# service to be assigned an external IP, then patch the ConfigMap.
# The make deploy-k8s-eks target calls this script BEFORE applying the overlay,
# so the NLB hostname isn't known yet. Instead we print instructions.
echo ""
echo "NOTE: After 'kubectl apply -k deploy/kubernetes/overlays/eks', wait for"
echo "      the Keycloak LoadBalancer hostname and run:"
echo ""
echo "  KC_HOST=\$(kubectl get svc keycloak -n finance -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
echo "  kubectl patch configmap app-config -n finance --type=merge \\"
echo "    -p \"{\\\"data\\\":{\\\"KEYCLOAK_PUBLIC_URL\\\":\\\"http://\$KC_HOST\\\"}}\""
echo "  kubectl rollout restart deployment/keycloak deployment/frontend -n finance"
